# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://github.com/CocoaPods/Specs.git'
target 'TestInfosysApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
platform :ios, '8.0'  
use_frameworks!
pod 'SDWebImage', '~> 5.0'
  # Pods for TestInfosysApplication
	
  target 'TestInfosysApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestInfosysApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
