# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestInfosysApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestInfosysApplication

  target 'TestInfosysApplicationTests' do
    inherit! :search_paths
    # Pods for testing
      pod 'SDWebImage', '~> 5.0'
  end

  target 'TestInfosysApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
